ProgrammersBlog/ProgrammersBlog.MVC/Areas/Admin/Controllers/RoleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Entities.Dtos;
using ProgrammersBlog.Mvc.Helpers.Abstract;
using ProgrammersBlog.MVC.Areas.Admin.Models;
using ProgrammersBlog.Shared.Utilities.Extansions;
using ProgrammersBlog.Shared.Utilities.Result.Complex_Types;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace ProgrammersBlog.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : BaseController
    {
        private readonly RoleManager<Role> _roleManager;

        public RoleController(RoleManager<Role> roleManager,UserManager<User> userManager,IMapper mapper,IImageHelper ımageHelper ):base(userManager,mapper,ımageHelper)
        {
            _roleManager = roleManager;
        }

        [Authorize(Roles="SuperAdmin,Role.Read")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
           
            return View(new RoleListDto
            {
                Roles = roles
            });
            
        }

        [Authorize(Roles = "SuperAdmin,Role.Read")]
        [HttpGet]
        public async Task<IActionResult> GetAllRoles()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            var roleListDto = JsonSerializer.Serialize(new RoleListDto
            {
                Roles = roles
            });
            return Json(roleListDto);
        }


        [Authorize(Roles = "SuperAdmin,User.Update")]
        [HttpGet]
        public async Task<IActionResult> Assign(int userId)
        {
            var roles = await _roleManager.Roles.ToListAsync();
            var user = await UserManager.Users.SingleOrDefaultAsync(c => c.Id == userId);
            var userroles = await UserManager.GetRolesAsync(user);

            UserRoleAssignDto userRoleAssiginDto = new UserRoleAssignDto
            {
                UserId = user.Id,
                UserName = user.UserName
            };

            foreach(var role in roles)
            {
                RoleAssignDto roleAssignDto = new RoleAssignDto
                {
                    RoleId = role.Id,
                    RoleName = role.Name,
                    HasRole = userroles.Contains(role.Name)
                };

                userRoleAssiginDto.RoleAssignDtos.Add(roleAssignDto);
                }

            return PartialView("_RoleAssignPartial", userRoleAssiginDto);
          }

        [Authorize(Roles = "SuperAdmin,User.Update")]
        [HttpPost]
        public async Task<IActionResult> Assign(UserRoleAssignDto userRoleAssignDto)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.Users.SingleOrDefaultAsync(x => x.Id == userRoleAssignDto.UserId);
                foreach (var roleAssiginDto in userRoleAssignDto.RoleAssignDtos)
                {
                    if (roleAssiginDto.HasRole == true)

                    {
                        await UserManager.AddToRoleAsync(user, roleAssiginDto.RoleName);
                    }

                    else
                    {
                        await UserManager.RemoveFromRoleAsync(user, roleAssiginDto.RoleName);
                    }
                }

                var userroleassignAjaxviewmodal = JsonSerializer.Serialize(new UserRoleAssiginAjaxViewModal
                {
                    UserDto = new UserDto
                    {
                        User = user,
                        Message = $"{user.UserName} Kullanıcısna ait Rol atama işlemi başarı ile gerçekleşti :)",
                        ResultStatus = ResultStatus.Success
                    },
                    UserRoleAssignPartial = await this.RenderViewToStringAsync("_RoleAssiginPartial", userRoleAssignDto)
                });
                return Json(userroleassignAjaxviewmodal);
                }

            else
            {
                var roleassiginajaxerrormodal = JsonSerializer.Serialize(new UserRoleAssiginAjaxViewModal
                {
                    UserRoleAssignPartial = await this.RenderViewToStringAsync("_RoleAssiginPartial", userRoleAssignDto),
                    userRoleAssiginDto = userRoleAssignDto
                });
                return Json(roleassiginajaxerrormodal);
            }

           }
        }
    }
      

ProgrammersBlog/ProgrammersBlog.MVC/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ProgrammersBlog.Entities.Complex_Type;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Entities.Dtos;
using ProgrammersBlog.MVC.Models;
using ProgrammersBlog.Sevices.Abstract;
using ProgrammersBlog.Shared.Utilities.Result.Complex_Types;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProgrammersBlog.MVC.Controllers
{
    
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly ArticleRightSideBarWidgetOptions _articleRightSideBarWidgetOptions;
        public ArticleController(IArticleService articleService, IOptionsSnapshot<ArticleRightSideBarWidgetOptions> articleRightSideBarWidgetOptions)
        {
            _articleService = articleService;
            _articleRightSideBarWidgetOptions = articleRightSideBarWidgetOptions.Value;
        }
        
        public async Task<IActionResult> Search(string keyword,int currenPage = 1 , int pageSize = 5 , bool isAscending = false)
        {
            var serachresult = await _articleService.SearchAsync(keyword, currenPage, pageSize, isAscending);
            if(serachresult.ResultStatus == ResultStatus.Success)
            {
             
                return View(new ArticleSearchViewModal() 
                {
                    ArticleListDto = serachresult.Data,
                    Keyword = keyword                  
                });
              
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int articleıd)
        {
            var articleResult = await _articleService.Get(articleıd);
            if (articleResult.ResultStatus == ResultStatus.Success)
            {
                var userArticles = await _articleService.GetAllByUserıdOnFilter(articleResult.Data.Article.UserId,
                    _articleRightSideBarWidgetOptions.FilterBy, _articleRightSideBarWidgetOptions.OrderBy, _articleRightSideBarWidgetOptions.IsAscending, _articleRightSideBarWidgetOptions.TakeSize, _articleRightSideBarWidgetOptions.CategoryId, _articleRightSideBarWidgetOptions.StartAt,
                    _articleRightSideBarWidgetOptions.EndAt, _articleRightSideBarWidgetOptions.MinViewCount, _articleRightSideBarWidgetOptions.MaxViewCount, _articleRightSideBarWidgetOptions.MinCommentCount, _articleRightSideBarWidgetOptions.MaxCommentCount);
                await _articleService.IncreaseViewCountAsync(articleıd);
                return View(new ArticleDetailViewModel
                {
                    ArticleDto = articleResult.Data,
                    ArticleDetailRightSideBarViewModel = new ArticleDetailRightSideBarViewModel
                    {
                        ArticleListDto = userArticles.Data,
                        Header = _articleRightSideBarWidgetOptions.Header,
                        User = articleResult.Data.Article.User
                    }
                });
            }

            return NotFound();
        }
    }
}

ProgrammersBlog/ProgrammersBlog.MVC/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Entities.Dtos;
using ProgrammersBlog.MVC.Models;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Extansions;
using ProgrammersBlog.Shared.Utilities.Result.Complex_Types;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace ProgrammersBlog.MVC.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }
        [HttpPost]
        public async Task<JsonResult> Add(CommentAddDto commentAddDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _commentService.AddAsync(commentAddDto);
                if (result.ResultStatus == ResultStatus.Success)
                {
                    var commentaddajaxviewmodal = JsonSerializer.Serialize(new CommentAddAjaxViewModal
                    {
                        CommentDto = result.Data,
                        CommentAddPartial = await this.RenderViewToStringAsync("_CommentAddPartial", commentAddDto)
                    }, new JsonSerializerOptions
                    {
                        ReferenceHandler = ReferenceHandler.Preserve
                    });
                    return Json(commentaddajaxviewmodal);
                }
                ModelState.AddModelError("", result.Message);
            }
                var commentaddajaxerrormodal = JsonSerializer.Serialize(new CommentAddAjaxViewModal
                {
                    CommemtAddDto = commentAddDto,
                    CommentAddPartial = await this.RenderViewToStringAsync("_CommentAddPartial", commentAddDto)
                });
                return Json(commentaddajaxerrormodal);
            }
         
        }
    }

ProgrammersBlog/ProgrammersBlog.MVC/Areas/Admin/Views/Shared/Components/AdminMenu/Default.cshtml
@model ProgrammersBlog.MVC.Areas.Admin.Models.UserWithRolesViewModel

<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">MENÜ</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Yönetim Paneli
                </a>
                <div class="sb-sidenav-menu-heading">İçerikler</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-th-list"></i></div>
                    Kategoriler
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Article" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-file-alt"></i></div>
                    Makaleler
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Comment" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-comments"></i></div>
                    Yorumlar
                </a>
                @if (Model.Roles.Any(r => r.Equals("SuperAdmin") || r.Equals("Role.Read")))
                {
                    <div class="sb-sidenav-menu-heading">Kullanıcılar</div>
                    <a class="nav-link" asp-area="Admin" asp-controller="Role" asp-action="Index">
                        <div class="sb-nav-link-icon"><i class="fas fa-user-shield"></i></div>
                        Roller
                    </a>
                }
                @if (Model.Roles.Any(r => r.Equals("SuperAdmin") || r.Equals("User.Read")))
                {
                    <a class="nav-link" asp-area="Admin" asp-controller="User" asp-action="Index">
                        <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                        Kullanıcılar
                    </a>

                    <div class="sb-sidenav-menu-heading">Ayarlar</div>
                    <a class="nav-link" asp-area="Admin" asp-controller="Options" asp-action="About">
                        <div class="sb-nav-link-icon"><i class="fas fa-tools"></i></div>
                        Hakkımızda Sayfa Ayarları ve içerikleri
                    </a>

                    <a class="nav-link" asp-area="Admin" asp-controller="Options" asp-action="EmailSettings">
                        <div class="sb-nav-link-icon"><i class="fas fa-envelope-open-text"></i></div>
                        E-Mail Ayarları
                    </a>

                    <a class="nav-link" asp-area="Admin" asp-controller="Options" asp-action="ArticleRightSideBarWidgetSettings">
                        <div class="sb-nav-link-icon"><i class="fas fa-tools"></i></div>
                        Makale Ayarları
                    </a>

                    <a class="nav-link" asp-area="Admin" asp-controller="Options" asp-action="GeneralSettings">
                        <div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>
                        Genel Ayarlar
                    </a>
                }
                <div class="sb-sidenav-menu-heading">Diger</div>
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-archive"></i></div>
                    Arşiv(Çöp Kutusu)
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="DeletedCategories">Kategoriler</a>
                        <a class="nav-link" asp-area="Admin" asp-controller="Article" asp-action="DeletedArticles">Makaleler</a>
                        <a class="nav-link" asp-area="Admin" asp-controller="Comment" asp-action="DeletedComments">Yorumlar</a>

                    </nav>
                </div>

            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Giriş Yapan Kullanıcı:  @Model.User.UserName  </div>
        
        </div>
    </nav>
</div>